//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the matches_conversion_ros_tool package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __matches_conversion_ros_tool__ADDOUTLIERFLAGCONFIG_H__
#define __matches_conversion_ros_tool__ADDOUTLIERFLAGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace matches_conversion_ros_tool
{
  class AddOutlierFlagConfigStatics;

  class AddOutlierFlagConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(AddOutlierFlagConfig &config, const AddOutlierFlagConfig &max, const AddOutlierFlagConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const AddOutlierFlagConfig &config1, const AddOutlierFlagConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, AddOutlierFlagConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const AddOutlierFlagConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AddOutlierFlagConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const AddOutlierFlagConfig &config) const = 0;
      virtual void getValue(const AddOutlierFlagConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T AddOutlierFlagConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (AddOutlierFlagConfig::* field);

      virtual void clamp(AddOutlierFlagConfig &config, const AddOutlierFlagConfig &max, const AddOutlierFlagConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const AddOutlierFlagConfig &config1, const AddOutlierFlagConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, AddOutlierFlagConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const AddOutlierFlagConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AddOutlierFlagConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const AddOutlierFlagConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const AddOutlierFlagConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, AddOutlierFlagConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, AddOutlierFlagConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(AddOutlierFlagConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("verbosity"==(*_i)->name){verbosity = boost::any_cast<std::string>(val);}
        if("has_depth"==(*_i)->name){has_depth = boost::any_cast<bool>(val);}
      }
    }

    std::string verbosity;
bool has_depth;

    bool state;
    std::string name;

    class PUBLISHER_AND_SUBSCRIBER
{
  public:
    PUBLISHER_AND_SUBSCRIBER()
    {
      state = true;
      name = "Publisher_and_subscriber";
    }

    void setParams(AddOutlierFlagConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("subscriber_depth_topic"==(*_i)->name){subscriber_depth_topic = boost::any_cast<std::string>(val);}
        if("subscriber_depth_queue_size"==(*_i)->name){subscriber_depth_queue_size = boost::any_cast<int>(val);}
        if("subscriber_topic"==(*_i)->name){subscriber_topic = boost::any_cast<std::string>(val);}
        if("subscriber_queue_size"==(*_i)->name){subscriber_queue_size = boost::any_cast<int>(val);}
        if("publisher_topic"==(*_i)->name){publisher_topic = boost::any_cast<std::string>(val);}
        if("publisher_queue_size"==(*_i)->name){publisher_queue_size = boost::any_cast<int>(val);}
      }
    }

    std::string subscriber_depth_topic;
int subscriber_depth_queue_size;
std::string subscriber_topic;
int subscriber_queue_size;
std::string publisher_topic;
int publisher_queue_size;

    bool state;
    std::string name;

    
}publisher_and_subscriber;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string verbosity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool has_depth;
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      std::string subscriber_depth_topic;
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      int subscriber_depth_queue_size;
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      std::string subscriber_topic;
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      int subscriber_queue_size;
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      std::string publisher_topic;
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      int publisher_queue_size;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("AddOutlierFlagConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const AddOutlierFlagConfig &__max__ = __getMax__();
      const AddOutlierFlagConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const AddOutlierFlagConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const AddOutlierFlagConfig &__getDefault__();
    static const AddOutlierFlagConfig &__getMax__();
    static const AddOutlierFlagConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const AddOutlierFlagConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void AddOutlierFlagConfig::ParamDescription<std::string>::clamp(AddOutlierFlagConfig &config, const AddOutlierFlagConfig &max, const AddOutlierFlagConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class AddOutlierFlagConfigStatics
  {
    friend class AddOutlierFlagConfig;

    AddOutlierFlagConfigStatics()
    {
AddOutlierFlagConfig::GroupDescription<AddOutlierFlagConfig::DEFAULT, AddOutlierFlagConfig> Default("Default", "", 0, 0, true, &AddOutlierFlagConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.verbosity = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.verbosity = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.verbosity = "info";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &AddOutlierFlagConfig::verbosity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &AddOutlierFlagConfig::verbosity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.has_depth = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.has_depth = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.has_depth = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<bool>("has_depth", "bool", 0, "Has input message depth?", "", &AddOutlierFlagConfig::has_depth)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<bool>("has_depth", "bool", 0, "Has input message depth?", "", &AddOutlierFlagConfig::has_depth)));
AddOutlierFlagConfig::GroupDescription<AddOutlierFlagConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, AddOutlierFlagConfig::DEFAULT> Publisher_and_subscriber("Publisher_and_subscriber", "", 0, 1, true, &AddOutlierFlagConfig::DEFAULT::publisher_and_subscriber);
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.subscriber_depth_topic = "";
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.subscriber_depth_topic = "";
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.subscriber_depth_topic = "in_topic_depth";
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("subscriber_depth_topic", "str", 0, "Topic for subscriber for matches with depth and without outliers", "", &AddOutlierFlagConfig::subscriber_depth_topic)));
//#line 24 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("subscriber_depth_topic", "str", 0, "Topic for subscriber for matches with depth and without outliers", "", &AddOutlierFlagConfig::subscriber_depth_topic)));
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.subscriber_depth_queue_size = 0;
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.subscriber_depth_queue_size = 2147483647;
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.subscriber_depth_queue_size = 5;
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("subscriber_depth_queue_size", "int", 0, "Queue size for subscriber for matches with depth and without outliers", "", &AddOutlierFlagConfig::subscriber_depth_queue_size)));
//#line 25 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("subscriber_depth_queue_size", "int", 0, "Queue size for subscriber for matches with depth and without outliers", "", &AddOutlierFlagConfig::subscriber_depth_queue_size)));
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.subscriber_topic = "";
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.subscriber_topic = "";
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.subscriber_topic = "in_topic";
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("subscriber_topic", "str", 0, "Topic for subscriber for matches without outliers", "", &AddOutlierFlagConfig::subscriber_topic)));
//#line 26 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("subscriber_topic", "str", 0, "Topic for subscriber for matches without outliers", "", &AddOutlierFlagConfig::subscriber_topic)));
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.subscriber_queue_size = 0;
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.subscriber_queue_size = 2147483647;
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.subscriber_queue_size = 5;
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("subscriber_queue_size", "int", 0, "Queue size for subscriber for matches without outliers", "", &AddOutlierFlagConfig::subscriber_queue_size)));
//#line 27 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("subscriber_queue_size", "int", 0, "Queue size for subscriber for matches without outliers", "", &AddOutlierFlagConfig::subscriber_queue_size)));
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.publisher_topic = "";
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.publisher_topic = "";
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.publisher_topic = "out_topic";
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("publisher_topic", "str", 0, "Topic for publisher for matches msg with outliers", "", &AddOutlierFlagConfig::publisher_topic)));
//#line 28 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<std::string>("publisher_topic", "str", 0, "Topic for publisher for matches msg with outliers", "", &AddOutlierFlagConfig::publisher_topic)));
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __min__.publisher_queue_size = 0;
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __max__.publisher_queue_size = 2147483647;
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __default__.publisher_queue_size = 5;
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("publisher_queue_size", "int", 0, "Queue size for publisher for matches msg with outliers", "", &AddOutlierFlagConfig::publisher_queue_size)));
//#line 29 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      __param_descriptions__.push_back(AddOutlierFlagConfig::AbstractParamDescriptionConstPtr(new AddOutlierFlagConfig::ParamDescription<int>("publisher_queue_size", "int", 0, "Queue size for publisher for matches msg with outliers", "", &AddOutlierFlagConfig::publisher_queue_size)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Publisher_and_subscriber.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr(new AddOutlierFlagConfig::GroupDescription<AddOutlierFlagConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, AddOutlierFlagConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr(new AddOutlierFlagConfig::GroupDescription<AddOutlierFlagConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, AddOutlierFlagConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr(new AddOutlierFlagConfig::GroupDescription<AddOutlierFlagConfig::DEFAULT, AddOutlierFlagConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<AddOutlierFlagConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    AddOutlierFlagConfig __max__;
    AddOutlierFlagConfig __min__;
    AddOutlierFlagConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const AddOutlierFlagConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static AddOutlierFlagConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &AddOutlierFlagConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const AddOutlierFlagConfig &AddOutlierFlagConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const AddOutlierFlagConfig &AddOutlierFlagConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const AddOutlierFlagConfig &AddOutlierFlagConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<AddOutlierFlagConfig::AbstractParamDescriptionConstPtr> &AddOutlierFlagConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<AddOutlierFlagConfig::AbstractGroupDescriptionConstPtr> &AddOutlierFlagConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const AddOutlierFlagConfigStatics *AddOutlierFlagConfig::__get_statics__()
  {
    const static AddOutlierFlagConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = AddOutlierFlagConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      const char * const AddOutlierFlag_debug = "debug";
//#line 16 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      const char * const AddOutlierFlag_info = "info";
//#line 17 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      const char * const AddOutlierFlag_warning = "warning";
//#line 18 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      const char * const AddOutlierFlag_error = "error";
//#line 19 "/home/dlx/catkin_limo_workspace/devel/share/matches_conversion_ros_tool/cfg/AddOutlierFlag.cfg"
      const char * const AddOutlierFlag_fatal = "fatal";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ADDOUTLIERFLAGRECONFIGURATOR_H__
