// *********************************************************
//
// File autogenerated for the matches_conversion_ros_tool package
// by the rosinterface_handler package.
// Please do not edit.
//
// ********************************************************/

#pragma once

#include <stdlib.h>
#include <string>
#include <limits>
#include <memory>
#include <ros/param.h>
#include <ros/node_handle.h>
#include <rosinterface_handler/console_bridge_compatibility.hpp>
#include <rosinterface_handler/utilities.hpp>
#ifdef MESSAGE_FILTERS_FOUND
#include <message_filters/subscriber.h>
#include <matches_msg_depth_ros/MatchesMsgWithOutlierFlag.h>
#include <sensor_msgs/Image.h>
#else
#error message_filters was not found during compilation. Please recompile with message_filters.
#endif
#ifdef DYNAMIC_RECONFIGURE_FOUND
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses"
#include <matches_conversion_ros_tool/SemanticLabelsConfig.h>
#pragma GCC diagnostic pop
#else
struct SemanticLabelsConfig{};
#endif


namespace matches_conversion_ros_tool {

/// \brief Parameter struct generated by rosinterface_handler
struct SemanticLabelsInterface {

  using Config = SemanticLabelsConfig;
#ifdef MESSAGE_FILTERS_FOUND
  template<typename T>
  using Subscriber = message_filters::Subscriber<T>;
  template<typename T>
  using SubscriberPtr = std::shared_ptr<Subscriber<T>>;
#endif
#ifdef IF_HANDLER_DIAGNOSTICS_INCLUDED
  template<typename T, typename BaseT = message_filters::Subscriber<T>>
  using DiagSubscriber = rosinterface_handler::DiagnosedSubscriber<T, BaseT>;
  template<typename T, typename BaseT = message_filters::Subscriber<T>>
  using DiagSubscriberPtr = std::shared_ptr<DiagSubscriber<T, BaseT>>;
  template<typename T>
  using DiagPublisher = rosinterface_handler::DiagnosedPublisher<T>;
#endif

  SemanticLabelsInterface(const ros::NodeHandle& private_node_handle)
  : globalNamespace_{"/"},
    publicNamespace_{rosinterface_handler::getParentNamespace(private_node_handle) + "/"},
    privateNamespace_{private_node_handle.getNamespace() + "/"},
    nodeName_{rosinterface_handler::getNodeName(private_node_handle)},
    privateNodeHandle_{private_node_handle},
    subscriber_matches{std::make_shared<Subscriber<matches_msg_depth_ros::MatchesMsgWithOutlierFlag>>()},
    subscriber_labels{std::make_shared<Subscriber<sensor_msgs::Image>>()} {}

  /// \brief Get values from parameter server
  ///
  /// Will fail if a value can not be found and no default value is given.
  void fromParamServer(){
    bool success = true;
    success &= rosinterface_handler::getParam(privateNamespace_ + "verbosity", verbosity, std::string{"info"});
    rosinterface_handler::setLoggerLevel(privateNodeHandle_, "verbosity", nodeName());
    rosinterface_handler::testConstParam(privateNamespace_ + "verbosity_debug");
    rosinterface_handler::testConstParam(privateNamespace_ + "verbosity_info");
    rosinterface_handler::testConstParam(privateNamespace_ + "verbosity_warning");
    rosinterface_handler::testConstParam(privateNamespace_ + "verbosity_error");
    rosinterface_handler::testConstParam(privateNamespace_ + "verbosity_fatal");
    success &= rosinterface_handler::getParam(privateNamespace_ + "roi_width", roi_width, int{5});
    success &= rosinterface_handler::getParam(privateNamespace_ + "roi_height", roi_height, int{5});
    success &= rosinterface_handler::getParam(privateNamespace_ + "subscriber_matches_topic", subscriber_matches_topic, std::string{"in_topic_matches"});
    success &= rosinterface_handler::getParam(privateNamespace_ + "subscriber_matches_queue_size", subscriber_matches_queue_size, int{5});
    success &= rosinterface_handler::getParam(privateNamespace_ + "subscriber_labels_topic", subscriber_labels_topic, std::string{"in_topic_semantic_labels"});
    success &= rosinterface_handler::getParam(privateNamespace_ + "subscriber_labels_queue_size", subscriber_labels_queue_size, int{5});
    success &= rosinterface_handler::getParam(privateNamespace_ + "matches_publisher_topic", matches_publisher_topic, std::string{"out_topic"});
    success &= rosinterface_handler::getParam(privateNamespace_ + "matches_publisher_queue_size", matches_publisher_queue_size, int{5});

    subscriber_matches->subscribe(privateNodeHandle_, rosinterface_handler::getTopic(privateNamespace_, subscriber_matches_topic), uint32_t(subscriber_matches_queue_size), ros::TransportHints().tcpNoDelay());
    subscriber_labels->subscribe(privateNodeHandle_, rosinterface_handler::getTopic(privateNamespace_, subscriber_labels_topic), uint32_t(subscriber_labels_queue_size), ros::TransportHints().tcpNoDelay());
    matches_publisher = privateNodeHandle_.advertise<matches_msg_depth_ros::MatchesMsgWithOutlierFlag>(rosinterface_handler::getTopic(privateNamespace_, matches_publisher_topic), matches_publisher_queue_size);

    rosinterface_handler::testMin<int>(privateNamespace_ + "roi_width", roi_width, 0);
    rosinterface_handler::testMax<int>(privateNamespace_ + "roi_width", roi_width, 50);
    rosinterface_handler::testMin<int>(privateNamespace_ + "roi_height", roi_height, 0);
    rosinterface_handler::testMax<int>(privateNamespace_ + "roi_height", roi_height, 50);
    rosinterface_handler::testMin<int>(privateNamespace_ + "subscriber_matches_queue_size", subscriber_matches_queue_size, 0);
    rosinterface_handler::testMin<int>(privateNamespace_ + "subscriber_labels_queue_size", subscriber_labels_queue_size, 0);
    rosinterface_handler::testMin<int>(privateNamespace_ + "matches_publisher_queue_size", matches_publisher_queue_size, 0);
    if(!success){
      missingParamsWarning();
      rosinterface_handler::exit("RosinterfaceHandler: GetParam could net retrieve parameter.");
    }
    ROS_DEBUG_STREAM(*this);
  }

  /// \brief Set parameters on ROS parameter server.
  void toParamServer(){
    rosinterface_handler::setParam(privateNamespace_ + "verbosity",verbosity);
    rosinterface_handler::setParam(privateNamespace_ + "roi_width",roi_width);
    rosinterface_handler::setParam(privateNamespace_ + "roi_height",roi_height);
    rosinterface_handler::setParam(privateNamespace_ + "subscriber_matches_topic",subscriber_matches_topic);
    rosinterface_handler::setParam(privateNamespace_ + "subscriber_matches_queue_size",subscriber_matches_queue_size);
    rosinterface_handler::setParam(privateNamespace_ + "subscriber_labels_topic",subscriber_labels_topic);
    rosinterface_handler::setParam(privateNamespace_ + "subscriber_labels_queue_size",subscriber_labels_queue_size);
    rosinterface_handler::setParam(privateNamespace_ + "matches_publisher_topic",matches_publisher_topic);
    rosinterface_handler::setParam(privateNamespace_ + "matches_publisher_queue_size",matches_publisher_queue_size);
  }

  /// \brief Update configurable parameters.
  ///
  /// \param config  dynamic reconfigure struct
  /// \level ?
  void fromConfig(const Config& config, const uint32_t level = 0){
#ifdef DYNAMIC_RECONFIGURE_FOUND
    if(subscriber_matches_topic != config.subscriber_matches_topic || subscriber_matches_queue_size != config.subscriber_matches_queue_size) {
      subscriber_matches->subscribe(privateNodeHandle_, rosinterface_handler::getTopic(privateNamespace_, config.subscriber_matches_topic), uint32_t(config.subscriber_matches_queue_size), ros::TransportHints().tcpNoDelay());
    }
    if(subscriber_labels_topic != config.subscriber_labels_topic || subscriber_labels_queue_size != config.subscriber_labels_queue_size) {
      subscriber_labels->subscribe(privateNodeHandle_, rosinterface_handler::getTopic(privateNamespace_, config.subscriber_labels_topic), uint32_t(config.subscriber_labels_queue_size), ros::TransportHints().tcpNoDelay());
    }
    if(matches_publisher_topic != config.matches_publisher_topic || matches_publisher_queue_size != config.matches_publisher_queue_size) {
      matches_publisher = privateNodeHandle_.advertise<matches_msg_depth_ros::MatchesMsgWithOutlierFlag>(rosinterface_handler::getTopic(privateNamespace_, config.matches_publisher_topic), config.matches_publisher_queue_size);
    }
    if(config.verbosity != this->verbosity) {
        rosinterface_handler::setParam(privateNamespace_ + "verbosity", config.verbosity);
        rosinterface_handler::setLoggerLevel(privateNodeHandle_, "verbosity");
    }
    verbosity = config.verbosity;
    roi_width = config.roi_width;
    roi_height = config.roi_height;
    subscriber_matches_topic = config.subscriber_matches_topic;
    subscriber_matches_queue_size = config.subscriber_matches_queue_size;
    subscriber_labels_topic = config.subscriber_labels_topic;
    subscriber_labels_queue_size = config.subscriber_labels_queue_size;
    matches_publisher_topic = config.matches_publisher_topic;
    matches_publisher_queue_size = config.matches_publisher_queue_size;
#else
  ROS_FATAL_STREAM("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
  rosinterface_handler::exit("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
#endif
  }

  /// \brief Stream operator for printing parameter struct
  friend std::ostream& operator<<(std::ostream& os, const SemanticLabelsInterface& p)
  {
    os << "[" << p.nodeName_ << "]\nNode " << p.nodeName_ << " has the following parameters:\n"
      << "	" << p.privateNamespace_ << "verbosity:" << p.verbosity << "\n"
      << "	" << p.privateNamespace_ << "verbosity_debug:" << p.verbosity_debug << "\n"
      << "	" << p.privateNamespace_ << "verbosity_info:" << p.verbosity_info << "\n"
      << "	" << p.privateNamespace_ << "verbosity_warning:" << p.verbosity_warning << "\n"
      << "	" << p.privateNamespace_ << "verbosity_error:" << p.verbosity_error << "\n"
      << "	" << p.privateNamespace_ << "verbosity_fatal:" << p.verbosity_fatal << "\n"
      << "	" << p.privateNamespace_ << "roi_width:" << p.roi_width << "\n"
      << "	" << p.privateNamespace_ << "roi_height:" << p.roi_height << "\n"
      << "	" << p.privateNamespace_ << "subscriber_matches_topic:" << p.subscriber_matches_topic << "\n"
      << "	" << p.privateNamespace_ << "subscriber_matches_queue_size:" << p.subscriber_matches_queue_size << "\n"
      << "	" << p.privateNamespace_ << "subscriber_labels_topic:" << p.subscriber_labels_topic << "\n"
      << "	" << p.privateNamespace_ << "subscriber_labels_queue_size:" << p.subscriber_labels_queue_size << "\n"
      << "	" << p.privateNamespace_ << "matches_publisher_topic:" << p.matches_publisher_topic << "\n"
      << "	" << p.privateNamespace_ << "matches_publisher_queue_size:" << p.matches_publisher_queue_size << "\n"
;
    return os;
  }

  /// \brief get the node handle that the interface struct uses internally
  ros::NodeHandle getPrivateNodeHandle() {
      return privateNodeHandle_;
  }

  /// \brief returns the name of the node (works in nodelets, too)
  const std::string& nodeName() const {
      return nodeName_;
  }

  /// \brief logs to the debug output. Works also within nodelets. Output is throttled.
  // NOLINTNEXTLINE(readability-function-size)
  inline void logDebug(const std::string& msg) const {
      ROS_DEBUG_STREAM_NAMED(nodeName(), msg);
  }

  /// \brief logs to the debug output. Works also within nodelets. Output is throttled.
  // NOLINTNEXTLINE(readability-function-size)
  inline void logInfo(const std::string& msg) const {
      ROS_INFO_STREAM_THROTTLE_NAMED(5, nodeName(), msg);
  }

  /// \brief logs to the debug output. Works also within nodelets. Output is throttled.
  // NOLINTNEXTLINE(readability-function-size)
  inline void logWarn(const std::string& msg) const {
      ROS_WARN_STREAM_THROTTLE_NAMED(5, nodeName(), msg);
  }

  /// \brief logs to the error output. Works also within nodelets. Output is throttled.
  // NOLINTNEXTLINE(readability-function-size)
  inline void logError(const std::string& msg) const {
      ROS_ERROR_STREAM_THROTTLE_NAMED(5, nodeName(), msg);
  }

  /// \brief logs to the error output. Works also within nodelets. Not throttled! Dont call this in loops!
  // NOLINTNEXTLINE(readability-function-size)
  inline void logErrorDirect(const std::string& msg) const {
      ROS_ERROR_STREAM_NAMED(nodeName(), msg);
  }
private:
  const std::string globalNamespace_;
  const std::string publicNamespace_;
  const std::string privateNamespace_;
  const std::string nodeName_;
  ros::NodeHandle privateNodeHandle_;

public:
  std::string verbosity; /*!< Sets the verbosity for this node */
  static constexpr auto verbosity_debug = "debug"; /*!< Constant for enum verbosity */
  static constexpr auto verbosity_info = "info"; /*!< Constant for enum verbosity */
  static constexpr auto verbosity_warning = "warning"; /*!< Constant for enum verbosity */
  static constexpr auto verbosity_error = "error"; /*!< Constant for enum verbosity */
  static constexpr auto verbosity_fatal = "fatal"; /*!< Constant for enum verbosity */
  int roi_width; /*!< width of roi to count labels */
  int roi_height; /*!< height of roi to count labels */
  std::string subscriber_matches_topic; /*!< Topic for subscriber with matches to assign label */
  int subscriber_matches_queue_size; /*!< Queue size for subscriber with matches to assign label */
  std::string subscriber_labels_topic; /*!< Topic for subscriber with matches to assign label */
  int subscriber_labels_queue_size; /*!< Queue size for subscriber with matches to assign label */
  std::string matches_publisher_topic; /*!< Topic for publisher with matches to assign label */
  int matches_publisher_queue_size; /*!< Queue size for publisher with matches to assign label */
  ros::Publisher matches_publisher; /*!< publisher with matches to assign label */
  SubscriberPtr<matches_msg_depth_ros::MatchesMsgWithOutlierFlag> subscriber_matches; /*!< subscriber with matches to assign label */
  SubscriberPtr<sensor_msgs::Image> subscriber_labels; /*!< subscriber with matches to assign label */

private:
  /// \brief Issue a warning about missing default parameters.
  void missingParamsWarning(){
    ROS_WARN_STREAM("[" << nodeName_ << "]\nThe following parameters do not have default values and need to be specified:\n"
    );
  }
};

} // namespace matches_conversion_ros_tool
