# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from matches_msg_ros/TrackletWithOutlierFlag.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import matches_msg_ros.msg

class TrackletWithOutlierFlag(genpy.Message):
  _md5sum = "b0850b41fae63a3817f19ea41f0d70c1"
  _type = "matches_msg_ros/TrackletWithOutlierFlag"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
# no header since shall not be transmitted individually
# Data field Tracklet
FeaturePoint[] feature_points

# flag if this tracklet is an outlier or not, default is false
bool is_outlier

# field for saving error, f.e. loss from optimization, the higher the value the higher the probability that it is an outlier, typically this is a relative value to the other errors
float32 error

# id given by tracker
uint64 id

# age of the tracklet
uint16 age

# label for the tracklet, LUT has to be provided by the user
int16 label

================================================================================
MSG: matches_msg_ros/FeaturePoint
# no header because shall not be send alone
# Data field Matches (as tracklets, el.first == u el.second == v)
float32 u
float32 v
"""
  __slots__ = ['feature_points','is_outlier','error','id','age','label']
  _slot_types = ['matches_msg_ros/FeaturePoint[]','bool','float32','uint64','uint16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       feature_points,is_outlier,error,id,age,label

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrackletWithOutlierFlag, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.feature_points is None:
        self.feature_points = []
      if self.is_outlier is None:
        self.is_outlier = False
      if self.error is None:
        self.error = 0.
      if self.id is None:
        self.id = 0
      if self.age is None:
        self.age = 0
      if self.label is None:
        self.label = 0
    else:
      self.feature_points = []
      self.is_outlier = False
      self.error = 0.
      self.id = 0
      self.age = 0
      self.label = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.feature_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.feature_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.u, _x.v))
      _x = self
      buff.write(_get_struct_BfQHh().pack(_x.is_outlier, _x.error, _x.id, _x.age, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.feature_points is None:
        self.feature_points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feature_points = []
      for i in range(0, length):
        val1 = matches_msg_ros.msg.FeaturePoint()
        _x = val1
        start = end
        end += 8
        (_x.u, _x.v,) = _get_struct_2f().unpack(str[start:end])
        self.feature_points.append(val1)
      _x = self
      start = end
      end += 17
      (_x.is_outlier, _x.error, _x.id, _x.age, _x.label,) = _get_struct_BfQHh().unpack(str[start:end])
      self.is_outlier = bool(self.is_outlier)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.feature_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.feature_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.u, _x.v))
      _x = self
      buff.write(_get_struct_BfQHh().pack(_x.is_outlier, _x.error, _x.id, _x.age, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.feature_points is None:
        self.feature_points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feature_points = []
      for i in range(0, length):
        val1 = matches_msg_ros.msg.FeaturePoint()
        _x = val1
        start = end
        end += 8
        (_x.u, _x.v,) = _get_struct_2f().unpack(str[start:end])
        self.feature_points.append(val1)
      _x = self
      start = end
      end += 17
      (_x.is_outlier, _x.error, _x.id, _x.age, _x.label,) = _get_struct_BfQHh().unpack(str[start:end])
      self.is_outlier = bool(self.is_outlier)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_BfQHh = None
def _get_struct_BfQHh():
    global _struct_BfQHh
    if _struct_BfQHh is None:
        _struct_BfQHh = struct.Struct("<BfQHh")
    return _struct_BfQHh
