(cl:defpackage matches_msg_depth_ros-msg
  (:use )
  (:export
   "<FEATUREPOINT>"
   "FEATUREPOINT"
   "<MATCHESMSG>"
   "MATCHESMSG"
   "<MATCHESMSGWITHINLIERFLAG>"
   "MATCHESMSGWITHINLIERFLAG"
   "<MATCHESMSGWITHOUTLIERFLAG>"
   "MATCHESMSGWITHOUTLIERFLAG"
   "<TRACKLET>"
   "TRACKLET"
   "<TRACKLETWITHINLIERFLAG>"
   "TRACKLETWITHINLIERFLAG"
   "<TRACKLETWITHOUTLIERFLAG>"
   "TRACKLETWITHOUTLIERFLAG"
  ))

