//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the viso_feature_tracking_ros_tool package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __viso_feature_tracking_ros_tool__FEATURETRACKINGCONTOURROICONFIG_H__
#define __viso_feature_tracking_ros_tool__FEATURETRACKINGCONTOURROICONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace viso_feature_tracking_ros_tool
{
  class FeatureTrackingContourRoiConfigStatics;

  class FeatureTrackingContourRoiConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(FeatureTrackingContourRoiConfig &config, const FeatureTrackingContourRoiConfig &max, const FeatureTrackingContourRoiConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const FeatureTrackingContourRoiConfig &config1, const FeatureTrackingContourRoiConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, FeatureTrackingContourRoiConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const FeatureTrackingContourRoiConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, FeatureTrackingContourRoiConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const FeatureTrackingContourRoiConfig &config) const = 0;
      virtual void getValue(const FeatureTrackingContourRoiConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T FeatureTrackingContourRoiConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (FeatureTrackingContourRoiConfig::* field);

      virtual void clamp(FeatureTrackingContourRoiConfig &config, const FeatureTrackingContourRoiConfig &max, const FeatureTrackingContourRoiConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const FeatureTrackingContourRoiConfig &config1, const FeatureTrackingContourRoiConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, FeatureTrackingContourRoiConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const FeatureTrackingContourRoiConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, FeatureTrackingContourRoiConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const FeatureTrackingContourRoiConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const FeatureTrackingContourRoiConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, FeatureTrackingContourRoiConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, FeatureTrackingContourRoiConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<FeatureTrackingContourRoiConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(FeatureTrackingContourRoiConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("verbosity"==(*_i)->name){verbosity = boost::any_cast<std::string>(val);}
        if("blur_size"==(*_i)->name){blur_size = boost::any_cast<int>(val);}
        if("blur_sigma"==(*_i)->name){blur_sigma = boost::any_cast<double>(val);}
        if("nms_n"==(*_i)->name){nms_n = boost::any_cast<int>(val);}
        if("nms_tau"==(*_i)->name){nms_tau = boost::any_cast<int>(val);}
        if("match_binsize"==(*_i)->name){match_binsize = boost::any_cast<int>(val);}
        if("match_radius"==(*_i)->name){match_radius = boost::any_cast<int>(val);}
        if("match_disp_tolerance"==(*_i)->name){match_disp_tolerance = boost::any_cast<int>(val);}
        if("outlier_flow_tolerance"==(*_i)->name){outlier_flow_tolerance = boost::any_cast<int>(val);}
        if("outlier_disp_tolerance"==(*_i)->name){outlier_disp_tolerance = boost::any_cast<int>(val);}
        if("multi_stage"==(*_i)->name){multi_stage = boost::any_cast<int>(val);}
        if("half_resolution"==(*_i)->name){half_resolution = boost::any_cast<int>(val);}
        if("max_tracklength"==(*_i)->name){max_tracklength = boost::any_cast<int>(val);}
      }
    }

    std::string verbosity;
int blur_size;
double blur_sigma;
int nms_n;
int nms_tau;
int match_binsize;
int match_radius;
int match_disp_tolerance;
int outlier_flow_tolerance;
int outlier_disp_tolerance;
int multi_stage;
int half_resolution;
int max_tracklength;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string verbosity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int blur_size;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double blur_sigma;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int nms_n;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int nms_tau;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int match_binsize;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int match_radius;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int match_disp_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int outlier_flow_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int outlier_disp_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int multi_stage;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int half_resolution;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_tracklength;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("FeatureTrackingContourRoiConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const FeatureTrackingContourRoiConfig &__max__ = __getMax__();
      const FeatureTrackingContourRoiConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const FeatureTrackingContourRoiConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const FeatureTrackingContourRoiConfig &__getDefault__();
    static const FeatureTrackingContourRoiConfig &__getMax__();
    static const FeatureTrackingContourRoiConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const FeatureTrackingContourRoiConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void FeatureTrackingContourRoiConfig::ParamDescription<std::string>::clamp(FeatureTrackingContourRoiConfig &config, const FeatureTrackingContourRoiConfig &max, const FeatureTrackingContourRoiConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class FeatureTrackingContourRoiConfigStatics
  {
    friend class FeatureTrackingContourRoiConfig;

    FeatureTrackingContourRoiConfigStatics()
    {
FeatureTrackingContourRoiConfig::GroupDescription<FeatureTrackingContourRoiConfig::DEFAULT, FeatureTrackingContourRoiConfig> Default("Default", "", 0, 0, true, &FeatureTrackingContourRoiConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.verbosity = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.verbosity = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.verbosity = "info";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &FeatureTrackingContourRoiConfig::verbosity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &FeatureTrackingContourRoiConfig::verbosity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.blur_size = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.blur_size = 21;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.blur_size = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("blur_size", "int", 0, "mask size of blurring", "", &FeatureTrackingContourRoiConfig::blur_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("blur_size", "int", 0, "mask size of blurring", "", &FeatureTrackingContourRoiConfig::blur_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.blur_sigma = 1e-05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.blur_sigma = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.blur_sigma = 0.8;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<double>("blur_sigma", "double", 0, "sigma of blurring", "", &FeatureTrackingContourRoiConfig::blur_sigma)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<double>("blur_sigma", "double", 0, "sigma of blurring", "", &FeatureTrackingContourRoiConfig::blur_sigma)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.nms_n = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.nms_n = 15;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.nms_n = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("nms_n", "int", 0, "non-max-suppression: min. distance between maxima (in pixels)", "", &FeatureTrackingContourRoiConfig::nms_n)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("nms_n", "int", 0, "non-max-suppression: min. distance between maxima (in pixels)", "", &FeatureTrackingContourRoiConfig::nms_n)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.nms_tau = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.nms_tau = 500;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.nms_tau = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("nms_tau", "int", 0, "non-max-suppression: interest point peakiness threshold", "", &FeatureTrackingContourRoiConfig::nms_tau)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("nms_tau", "int", 0, "non-max-suppression: interest point peakiness threshold", "", &FeatureTrackingContourRoiConfig::nms_tau)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.match_binsize = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.match_binsize = 1500;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.match_binsize = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_binsize", "int", 0, "matching bin width/height (affects efficiency only)", "", &FeatureTrackingContourRoiConfig::match_binsize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_binsize", "int", 0, "matching bin width/height (affects efficiency only)", "", &FeatureTrackingContourRoiConfig::match_binsize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.match_radius = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.match_radius = 1500;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.match_radius = 200;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_radius", "int", 0, "matching radius (du/dv in pixels)", "", &FeatureTrackingContourRoiConfig::match_radius)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_radius", "int", 0, "matching radius (du/dv in pixels)", "", &FeatureTrackingContourRoiConfig::match_radius)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.match_disp_tolerance = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.match_disp_tolerance = 21;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.match_disp_tolerance = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_disp_tolerance", "int", 0, "dv tolerance for stereo matches (in pixels)", "", &FeatureTrackingContourRoiConfig::match_disp_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("match_disp_tolerance", "int", 0, "dv tolerance for stereo matches (in pixels)", "", &FeatureTrackingContourRoiConfig::match_disp_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.outlier_flow_tolerance = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.outlier_flow_tolerance = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.outlier_flow_tolerance = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("outlier_flow_tolerance", "int", 0, "outlier removal: flow tolerance (in pixels)", "", &FeatureTrackingContourRoiConfig::outlier_flow_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("outlier_flow_tolerance", "int", 0, "outlier removal: flow tolerance (in pixels)", "", &FeatureTrackingContourRoiConfig::outlier_flow_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.outlier_disp_tolerance = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.outlier_disp_tolerance = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.outlier_disp_tolerance = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("outlier_disp_tolerance", "int", 0, "outlier removal: disparity tolerance (in pixels)", "", &FeatureTrackingContourRoiConfig::outlier_disp_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("outlier_disp_tolerance", "int", 0, "outlier removal: disparity tolerance (in pixels)", "", &FeatureTrackingContourRoiConfig::outlier_disp_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.multi_stage = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.multi_stage = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.multi_stage = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("multi_stage", "int", 0, " 0=disabled,1=multistage matching (denser and faster)", "", &FeatureTrackingContourRoiConfig::multi_stage)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("multi_stage", "int", 0, " 0=disabled,1=multistage matching (denser and faster)", "", &FeatureTrackingContourRoiConfig::multi_stage)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.half_resolution = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.half_resolution = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.half_resolution = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("half_resolution", "int", 0, " 0=disabled,1=match at half resolution, refine at full resolution", "", &FeatureTrackingContourRoiConfig::half_resolution)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("half_resolution", "int", 0, " 0=disabled,1=match at half resolution, refine at full resolution", "", &FeatureTrackingContourRoiConfig::half_resolution)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_tracklength = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_tracklength = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_tracklength = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("max_tracklength", "int", 0, "older detections of one feature than this age are discarded", "", &FeatureTrackingContourRoiConfig::max_tracklength)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr(new FeatureTrackingContourRoiConfig::ParamDescription<int>("max_tracklength", "int", 0, "older detections of one feature than this age are discarded", "", &FeatureTrackingContourRoiConfig::max_tracklength)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(FeatureTrackingContourRoiConfig::AbstractGroupDescriptionConstPtr(new FeatureTrackingContourRoiConfig::GroupDescription<FeatureTrackingContourRoiConfig::DEFAULT, FeatureTrackingContourRoiConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<FeatureTrackingContourRoiConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<FeatureTrackingContourRoiConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    FeatureTrackingContourRoiConfig __max__;
    FeatureTrackingContourRoiConfig __min__;
    FeatureTrackingContourRoiConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const FeatureTrackingContourRoiConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static FeatureTrackingContourRoiConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &FeatureTrackingContourRoiConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const FeatureTrackingContourRoiConfig &FeatureTrackingContourRoiConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const FeatureTrackingContourRoiConfig &FeatureTrackingContourRoiConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const FeatureTrackingContourRoiConfig &FeatureTrackingContourRoiConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<FeatureTrackingContourRoiConfig::AbstractParamDescriptionConstPtr> &FeatureTrackingContourRoiConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<FeatureTrackingContourRoiConfig::AbstractGroupDescriptionConstPtr> &FeatureTrackingContourRoiConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const FeatureTrackingContourRoiConfigStatics *FeatureTrackingContourRoiConfig::__get_statics__()
  {
    const static FeatureTrackingContourRoiConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = FeatureTrackingContourRoiConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg"
      const char * const FeatureTrackingContourRoi_debug = "debug";
//#line 16 "/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg"
      const char * const FeatureTrackingContourRoi_info = "info";
//#line 17 "/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg"
      const char * const FeatureTrackingContourRoi_warning = "warning";
//#line 18 "/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg"
      const char * const FeatureTrackingContourRoi_error = "error";
//#line 19 "/home/dlx/catkin_limo_workspace/devel/share/viso_feature_tracking_ros_tool/cfg/FeatureTrackingContourRoi.cfg"
      const char * const FeatureTrackingContourRoi_fatal = "fatal";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __FEATURETRACKINGCONTOURROIRECONFIGURATOR_H__
